services:
  - type: web
    name: portfolio-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
